### ISSUE TITLE
Some open onload

### ISSUE THREAD

**Issue by Swiek** [lukesnowden/magic-accordion#3]
Hi,

Is it possible to show some as open on load and others as closed?

Kind regards,

Erwin

**Comment by lukesnowden** [comment]
https://github.com/lukesnowden/magic-accordion/blob/master/jquery.magic-accordion.js#L20 :-)

**Comment by Swiek** [comment]
Then they are all open. I am looking for a way to only open the relevant ones.

So for example we have 6 hidden accordions but i want to op 3 of them.

**Comment by lukesnowden** [comment]
Ah then no mate sorry.  

## 

Luke Snowden
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Swiek** [comment]
Have you ever seen this behaviour?

http://www.doublemedia.nl/magic.mp4

**Comment by lukesnowden** [comment]
I've never seen that before no. Have you got this hosted someplace?

**Comment by Swiek** [comment]
Yes I do. Go to https://www.rchelicoptershop.nl/quadcopters/udi-u818a-quadcopter and resize to mobile size. And refresh. Try the item Specificaties.

**Comment by lukesnowden** [comment]
``` css
@media only screen and (max-width: 991px)
.sidebar-box {
    -webkit-transition: all 0.5s ease-in-out;
    -o-transition: all 0.5s ease-in-out;
    transition: all 0.5s ease-in-out;
    -webket-transition: all 0.5s ease-in-out;
    /* height: 150px; */
    position: relative;
    overflow: hidden;
}
```

think thats your problem mate
